version: "3"

# Future: https://gist.github.com/leonsteinhaeuser/745f541517a9cc3bb78b565158e5a42c

services:
  # dependencies
  postgres-1:
    container_name: &pg_host postgres-1
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user article_service
      POSTGRES_PASSWORD: &pg_pass article_service
      POSTGRES_DB: &pg_db article_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-1
    volumes:
      - postgres-data-1:/var/lib/postgresql/data/pgdata
  postgres-2:
    container_name: &pg_host2 postgres-2
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user2 user_service
      POSTGRES_PASSWORD: &pg_pass2 user_service
      POSTGRES_DB: &pg_db2 user_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-2
    volumes:
      - postgres-data-2:/var/lib/postgresql/data/pgdata
  postgres-3:
    container_name: &pg_host3 postgres-3
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user3 keyword_service
      POSTGRES_PASSWORD: &pg_pass3 keyword_service
      POSTGRES_DB: &pg_db3 keyword_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-3
    volumes:
      - postgres-data-3:/var/lib/postgresql/data/pgdata
  postgres-4:
    container_name: &pg_host4 postgres-4
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user4 articlecomment_service
      POSTGRES_PASSWORD: &pg_pass4 articlecomment_service
      POSTGRES_DB: &pg_db4 articlecomment_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-4
    volumes:
      - postgres-data-4:/var/lib/postgresql/data/pgdata
  yugabyte-2:
    container_name: &yb_host_2 yugabyte-2
    image: yugabytedb/yugabyte
    ports:
      - 7000:7000 # YB-Master UI
      - 9000:9000 # YB-TServer UI
      - 5433:5433 # YSQL-PostgreSQL API
      - 9042:9042 # YCQL-Cassandra API
    networks:
      - pgsql-2
      - yb
    command: bin/yugabyted start --advertise_address=0.0.0.0 --daemon=false --base_dir=/home/yugabyte/yb_data
    volumes:
      - ybdata:/home/yugabyte/yb_data
  init-yugabyte-2:
    container_name: init-yugabyte-2
    image: yugabytedb/yugabyte-client
    depends_on:
      - yugabyte-2
    networks:
      - yb
    volumes:
      - ./scripts:/srv/scripts
    entrypoint: /home/yugabyte/bin/ysqlsh
    command:
    - -h "yugabyte-2"
    - -p "5433"
    - -U "yugabyte"
    - -w "yugabyte"
    - -f /srv/scripts/init_db_user_service.sql
  nats-0:
    image: nats
    container_name: nats-0
    ports:
    #  - "4222:4222" # clients
      - "8222:8222" # HTTP management port for information reporting
    #  - "6222:6222" # routing port for clustering
    command: --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --user=nats --pass=nats
    networks:
      - nats
  nats-1:
    image: nats
    container_name: nats-1
    command: --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222
    networks:
      - nats
    depends_on:
    - "nats-0"
  nats-2:
    image: nats
    container_name: nats-2
    command: --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222
    networks:
      - nats
    depends_on:
    - "nats-0"
  # services
  number-service:
    container_name: name-service
    build:
      context: .
      dockerfile: ./number-service/Dockerfile
    networks:
      - app
  view-service:
    container_name: view-service
    build:
      context: .
      dockerfile: ./view-service/Dockerfile
    environment:
      NUMBER_SERVICE_ADDRESS: "http://number-service:1111"
      ARTICLE_SERVICE_URL: "http://article-service:3333"
      USER_SERVICE_URL: "http://user-service:4444"
    networks:
      - app
    ports:
      - "2222:2222"
  article-service:
    container_name: article-service
    build:
      context: .
      dockerfile: ./article-service/Dockerfile
    depends_on:
      nats-0:
        condition: service_started
      nats-1:
        condition: service_started
      nats-2:
        condition: service_started
      postgres-1:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user
      DATABASE_PASSWORD: *pg_pass
      DATABASE_NAME: *pg_db
      DATABASE_OPTIONS: sslmode=disable
      NATS_URL: "nats://nats:nats@nats-0:4222,nats://nats:nats@nats-1:4222,nats://nats:nats@nats-2:4222"
    networks:
      - app
      - pgsql-1
      - nats
    ports:
      - "13333:3333"
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    depends_on:
      postgres-2:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host2
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user2
      DATABASE_PASSWORD: *pg_pass2
      DATABASE_NAME: *pg_db2
      DATABASE_OPTIONS: sslmode=disable
    networks:
      - app
      - pgsql-2
      - nats
    #ports:
    #  - "4444:4444"
  keyword-service:
    container_name: keyword-service
    build:
      context: .
      dockerfile: ./keyword-service/Dockerfile
    depends_on:
      postgres-3:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host3
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user3
      DATABASE_PASSWORD: *pg_pass3
      DATABASE_NAME: *pg_db3
      DATABASE_OPTIONS: sslmode=disable
    networks:
      - app
      - pgsql-3
      - nats
    ports:
      - "5555:5555"
  articlecomment-service:
    container_name: articlecomment-service
    build:
      context: .
      dockerfile: ./articlecomment-service/Dockerfile
    depends_on:
      postgres-4:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host4
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user4
      DATABASE_PASSWORD: *pg_pass4
      DATABASE_NAME: *pg_db4
      DATABASE_OPTIONS: sslmode=disable
    networks:
      - app
      - pgsql-4
      - nats
    ports:
      - "6666:6666"
  article-consumer-service:
    container_name: article-consumer-service
    build:
      context: .
      dockerfile: ./article-consumer-service/Dockerfile
    depends_on:
      nats-0:
        condition: service_started
      nats-1:
        condition: service_started
      nats-2:
        condition: service_started
    environment:
      NATS_URL: "nats://nats:nats@nats-0:4222,nats://nats:nats@nats-1:4222,nats://nats:nats@nats-2:4222"
      ARTICLE_COMMENT_SERVICE_URL: "http://articlecomment-service:6666"
    networks:
      - app
      - nats
    #ports:
    #  - "7777:7777"


networks:
  app:
  pgsql-1:
  pgsql-2:
  pgsql-3:
  pgsql-4:
  nats:
  yb:

volumes:
  postgres-data-1:
  postgres-data-2:
  postgres-data-3:
  postgres-data-4:
  ybdata: