version: "3"

# Future: https://gist.github.com/leonsteinhaeuser/745f541517a9cc3bb78b565158e5a42c

services:
  # dependencies
  postgres-1:
    container_name: &pg_host postgres-1
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user article_service
      POSTGRES_PASSWORD: &pg_pass article_service
      POSTGRES_DB: &pg_db article_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-1
    volumes:
      - postgres-data-1:/var/lib/postgresql/data/pgdata
  postgres-2:
    container_name: &pg_host2 postgres-2
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: &pg_user2 user_service
      POSTGRES_PASSWORD: &pg_pass2 user_service
      POSTGRES_DB: &pg_db2 user_service
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pgsql-2
    volumes:
      - postgres-data-2:/var/lib/postgresql/data/pgdata

  yugabyte-2:
    container_name: &yb_host_2 yugabyte-2
    image: yugabytedb/yugabyte
    ports:
      - 7000:7000 # YB-Master UI
      - 9000:9000 # YB-TServer UI
      - 5433:5433 # YSQL-PostgreSQL API
      - 9042:9042 # YCQL-Cassandra API
    networks:
      - pgsql-2
      - yb
    command: bin/yugabyted start --advertise_address=0.0.0.0 --daemon=false --base_dir=/home/yugabyte/yb_data
    volumes:
      - ybdata:/home/yugabyte/yb_data

  init-yugabyte-2:
    container_name: init-yugabyte-2
    image: yugabytedb/yugabyte-client
    depends_on:
      - yugabyte-2
    networks:
      - yb
    volumes:
      - ./scripts:/srv/scripts
    entrypoint: /home/yugabyte/bin/ysqlsh
    command:
    - -h "yugabyte-2"
    - -p "5433"
    - -U "yugabyte"
    - -w "yugabyte"
    - -f /srv/scripts/init_db_user_service.sql

  nats-1:
    image: nats:2.9.16-alpine
    container_name: nats-1
    #ports:
    #  - "4222:4222"
    #  - "8222:8222"
    #  - "6222:6222"
    command:
      - --user=nats
      - --pass=nats
      - --server_name=nats
    networks:
      - nats-1

  # services
  number-service:
    container_name: name-service
    build:
      context: .
      dockerfile: ./number-service/Dockerfile
    networks:
      - app

  view-service:
    container_name: view-service
    build:
      context: .
      dockerfile: ./view-service/Dockerfile
    environment:
      NUMBER_SERVICE_ADDRESS: "http://number-service:1111"
      ARTICLE_SERVICE_URL: "http://article-service:3333"
    networks:
      - app
    ports:
      - "2222:2222"

  article-service:
    container_name: article-service
    build:
      context: .
      dockerfile: ./article-service/Dockerfile
    depends_on:
      #init-database:
      #  condition: service_completed_successfully
      postgres-1:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user
      DATABASE_PASSWORD: *pg_pass
      DATABASE_NAME: *pg_db
      DATABASE_OPTIONS: sslmode=disable
    networks:
      - app
      - pgsql-1
      - nats-1
    ports:
      - "13333:3333"

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    depends_on:
      postgres-2:
        condition: service_started
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: *pg_host2
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: *pg_user2
      DATABASE_PASSWORD: *pg_pass2
      DATABASE_NAME: *pg_db2
      DATABASE_OPTIONS: sslmode=disable
    networks:
      - app
      - pgsql-2
      - nats-1
    #ports:
    #  - "4444:4444"

networks:
  app:
  pgsql-1:
  pgsql-2:
  nats-1:
  yb:

volumes:
  postgres-data-1:
  postgres-data-2:
  ybdata: