// Code generated by swaggo/swag at 2023-07-05 22:12:19.202488 +0200 CEST m=+0.140149801. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://github.com/leonsteinhaeuser/example-app",
            "email": "mail@example.localhost"
        },
        "license": {
            "name": "GNU GENERAL PUBLIC LICENSE 3.0",
            "url": "https://github.com/leonsteinhaeuser/example-app/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "thread-view-service",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Thread View Service",
	Description:      "This is the thread-view-service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
