basePath: /
definitions:
  thread.Thread:
    properties:
      author_id:
        type: string
      body:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      keyword_ids:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  utils.HTTPError:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
host: thread-service
info:
  contact:
    email: mail@example.localhost
    name: API Support
    url: http://github.com/leonsteinhaeuser/example-app
  description: This is the thread-service.
  license:
    name: GNU GENERAL PUBLIC LICENSE 3.0
    url: https://github.com/leonsteinhaeuser/example-app/blob/main/LICENSE
  title: Thread Service API
  version: "1.0"
paths:
  /thread:
    get:
      consumes:
      - application/json
      description: List all threads
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/thread.Thread'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: List all threads
      tags:
      - thread
    post:
      consumes:
      - application/json
      description: Create a thread
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thread.Thread'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Create a thread
      tags:
      - thread
  /thread/{id}:
    delete:
      consumes:
      - application/json
      description: Deleteh a thread
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thread.Thread'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Deleteh a thread
      tags:
      - thread
    get:
      consumes:
      - application/json
      description: Get thread by ID
      parameters:
      - description: find thread b ID
        format: uuid
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thread.Thread'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Get thread by ID
      tags:
      - thread
    put:
      consumes:
      - application/json
      description: Update a thread
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thread.Thread'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Update a thread
      tags:
      - thread
swagger: "2.0"
